v1.1.6
New transformers:
- BlockHealthSystem
- GamePacketHandler

Potencial fixes for:

java.lang.NullPointerException: Cannot invoke "com.hypixel.hytale.server.core.entity.entities.Player.isWaitingForClientReady()" because "playerComponent" is null

and

java.lang.NullPointerException: Cannot invoke "com.hypixel.hytale.server.spawning.world.component.ChunkSpawnData.getEnvironmentSpawnData(int)" because "chunkSpawnDataComponent" is null